server:
  port: 8761
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka01
    prefer-ip-address: true
    instance-id: 192.168.170.97:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/

