server:
  port: 7070

spring:
  application:
    name: service-pricider #\u5E94\u7528\u540D\u79F0

eureka:
  instance:
    prefer-ip-address: true #\u662F\u5426\u4F7F\u7528ip\u5730\u5740\u6CE8\u518C
    instance-id: 192.168.170.97:${server.port}
  client:
    service-url:                  #\u6CE8\u518C\u4E2D\u5FC3\u5BF9\u5916\u66B4\u6F0F\u7684\u6CE8\u518C\u5730\u5740
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/