server:
  port: 8762
spring:
  application:
    name: eureka-server #应用名称
#配置Eureka server注册中心
eureka:
  instance:
    hostname: eureka02 #主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true #是否使用ip地址注册
    instance-id: 192.168.170.97:${server.port}
  client:
    register-with-eureka: true #是否将自己注册的注册中心，默认为true，单节点需要关闭，多节点开启
    fetch-registry: true        #是否从注册中心获取注册信息，默认为true，单节点需要关闭，多节点开启
    service-url:                  #注册中心对外暴漏的注册地址
      defaultZone: http://localhost:8761/eureka/

